name: 'Terraform Manual Actions'

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Select Action to Perform'
        required: true
        options:
          - create
          - destroy

permissions:
  contents: write
  pull-requests: write

env:
  TF_LOG: INFO
  TF_VAR_repositories: '["xxx", "yyy", "zzz"]'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.1"

      - name: Read Previous State Location
        id: state-location
        run: |
          if [ -f "terraform.state.link" ]; then
            echo "previous_run_id=$(grep 'run_id:' terraform.state.link | cut -d' ' -f2)" >> $GITHUB_OUTPUT
            echo "previous_workflow=$(grep 'workflow_id:' terraform.state.link | cut -d' ' -f2)" >> $GITHUB_OUTPUT
            echo "previous_artifact_id=$(grep 'artifact_id:' terraform.state.link | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          fi

      - name: Download Previous State
        if: steps.state-location.outputs.previous_artifact_id != ''
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: terraform-state
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.state-location.outputs.previous_run_id }}

      - name: Verify State File Download
        if: steps.state-location.outputs.previous_artifact_id != ''
        run: |
          echo -e "Directory contents:\n"
          ls -la
          echo -e "\nTerraform state file contents:\n"
          cat terraform.tfstate || echo "State file not found"

      - name: Initialize Empty State
        if: github.event.inputs.action == 'create' && hashFiles('terraform.tfstate') == ''
        run: |
          echo '{
            "version": 4,
            "terraform_version": "1.12.1",
            "serial": 1,
            "lineage": "'$(uuidgen)'",
            "outputs": {},
            "resources": [],
            "check_results": null
          }' > terraform.tfstate

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: Terraform Plan Create
        if: github.event.inputs.action == 'create'
        id: plan
        run: terraform plan -no-color -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}

      - name: Terraform Plan Destroy
        if: github.event.inputs.action == 'destroy'
        id: plan-destroy
        continue-on-error: true
        run: terraform plan -destroy -no-color -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'create'
        run: terraform apply -auto-approve -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        continue-on-error: true
        run: |
          #curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/etc/apt/keyrings/githubcli-archive-keyring.gpg
          #echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/githubcli.list > /dev/null
          sudo apt update
          sudo apt install gh
          
          # Unset GITHUB_TOKEN to avoid conflicts with gh auth
          #unset GITHUB_TOKEN
          
          echo "${{ secrets.TF_GITHUB_TOKEN }}" | gh auth login --with-token
          #gh auth login --with-token

          # Convert JSON array to bash array and iterate
          repositories=$(echo $TF_VAR_repositories | jq -r '.[]')
          for repo in $repositories; do
            gh repo delete ${{ github.repository_owner }}/$repo --yes || true
          done

          # Destroy all resources
          terraform destroy -auto-approve -input=false
        env:
          #GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_token: ${{ secrets.TF_GITHUB_TOKEN }}
          TF_VAR_github_owner: ${{ github.repository_owner }}

      - name: Upload State
        if: always()
        id: upload-state
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform.tfstate
          retention-days: 90
          if-no-files-found: error

      - name: Get Artifact ID
        if: success()
        id: artifact
        run: |
          # Wait a moment for the artifact to be processed
          sleep 5
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" | \
            jq -r '.artifacts[] | select(.name=="terraform-state") | .id')
          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: Update State Link
        if: success()
        run: |
          echo "run_id: ${{ github.run_id }}" > terraform.state.link
          echo "workflow_id: ${{ github.workflow }}" >> terraform.state.link
          echo "artifact_id: ${{ steps.artifact.outputs.artifact_id }}" >> terraform.state.link
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add terraform.state.link
          git commit -m "Update terraform state location [skip ci]" || true
          git push